# Generated by Django 3.1 on 2023-11-30 17:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("staff", "Staff"),
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                        ],
                        default="user",
                        max_length=60,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("USA", "United States"),
                            ("CAN", "Canada"),
                            ("GBR", "United Kingdom"),
                            ("AUS", "Australia"),
                            ("GER", "Germany"),
                            ("FRA", "France"),
                            ("IND", "India"),
                            ("JPN", "Japan"),
                            ("BRA", "Brazil"),
                            ("CHN", "China"),
                            ("RUS", "Russia"),
                            ("ZAF", "South Africa"),
                            ("MEX", "Mexico"),
                            ("ITA", "Italy"),
                            ("ESP", "Spain"),
                            ("ARG", "Argentina"),
                            ("NLD", "Netherlands"),
                            ("NZL", "New Zealand"),
                            ("SWE", "Sweden"),
                            ("CHE", "Switzerland"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("USA", "American"),
                            ("CAN", "Canadian"),
                            ("GBR", "British"),
                            ("AUS", "Australian"),
                            ("GER", "German"),
                            ("FRA", "French"),
                            ("IND", "Indian"),
                            ("JPN", "Japanese"),
                            ("BRA", "Brazilian"),
                            ("CHN", "Chinese"),
                            ("RUS", "Russian"),
                            ("ZAF", "South African"),
                            ("MEX", "Mexican"),
                            ("ITA", "Italian"),
                            ("ESP", "Spanish"),
                            ("ARG", "Argentinian"),
                            ("NLD", "Dutch"),
                            ("NZL", "New Zealander"),
                            ("SWE", "Swedish"),
                            ("CHE", "Swiss"),
                        ],
                        max_length=100,
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
